### ISSUE TITLE
Sending PATCH request Error: Bad Request

### ISSUE THREAD

**Issue by acouvreur** [peter-evans/dockerhub-description#147]
As you can see here https://github.com/acouvreur/sablier/actions/runs/4646770934/jobs/8223387131

![image](https://user-images.githubusercontent.com/22034450/230795496-501a18c3-bea8-4526-81e1-e061cd9c20a5.png)

> Reading description source file
Warning: The short description exceeds DockerHub's limit and has been truncated to 100 bytes.
Acquiring token
Sending PATCH request
Error: Bad Request

I did re-run it with debug logging for the following job:
https://github.com/acouvreur/sablier/actions/runs/4646770934/jobs/8232625295

And you can see this: 

> ##[debug]Error: Bad Request
##[debug]    at /home/runner/work/_actions/peter-evans/dockerhub-description/v3/dist/index.js:82:23
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Do you have any idea why it doesn't work as it used to work before?

**Comment by peter-evans** [comment]
Hi @acouvreur 

Apologies. I made a silly error in the last release. I've just fixed it in `v3.4.1` / `v3`.

Just to be clear, though. Your description will still be truncated because it does exceed the limit DockerHub allows. The bug was just a silly error where I failed to actually use the truncated version. 🙃 

Thank you for reporting this issue.

**Comment by acouvreur** [comment]
Thank you very much!
