### ISSUE TITLE
ENOENT: no such file or directory, open './README.md'

### ISSUE THREAD

**Issue by b-reich** [peter-evans/dockerhub-description#32]
I got "ENOENT: no such file or directory, open './README.md'"

My Repo: https://github.com/b-reich/latex-docker

**Comment by peter-evans** [comment]
Hi @b-reich 

You need to checkout your repository during the workflow, otherwise the action won't find your readme file.

Add this step before running the action.
```yml
- uses: actions/checkout@v2
```

**Comment by TimPietrusky** [comment]
@peter-evans I wonder how it can be possible that nothing checks out the repo? How does docker build work when the repo is not available? This is not your fault or anything, I guess it would be just nice if there would be a more prominent message in the "usage" section of your README, so that people don't have to run into this problem first, then find this issue and then add the action to checkout. It would be faster, but I understand if you don't want to do this 🙏

**Comment by peter-evans** [comment]
@TimPietrusky The action requires the repository to be checked out locally (on the runner), otherwise it can't find your readme.

I've updated the usage section of the readme to make this more clear.
https://github.com/peter-evans/dockerhub-description#usage

**Comment by TimPietrusky** [comment]
@peter-evans thank you very much <3
