### ISSUE TITLE
Suddenly receiving 401 response code

### ISSUE THREAD

**Issue by Erikvl87** [peter-evans/dockerhub-description#7]
Hello Peter,

I have been using your GitHub Action with success in the past; but somehow it broke down (or I broke it 😉). I have a 2FA enabled Docker Hub account and have set `DOCKERHUB_PASSWORD` secret in GitHub with my account password (not the personal access token, as instructed in your README.md).

The response I am receiving:
```
Acquiring token
Sending PATCH request
Received response code: 401
##[error]Docker run failed with exit code 1
```
Link to a successful run 6 weeks ago: [action](https://github.com/Erikvl87/docker-languagetool/commit/d559163f80978f54ff3770c5a8927f4402ffdd4b/checks?check_suite_id=309681864)
Link to an unsuccessful run today: [action](https://github.com/Erikvl87/docker-languagetool/commit/e282677274025ed78a18dc1729c3d9918d173efb/checks?check_suite_id=376838744)

Could you help me resolve the issue? I suspect there is something wrong in the API communication since I haven't made any changes to the Github Action .yml file.

**Comment by peter-evans** [comment]
Hi @Erikvl87 

This is due to  recent changes by Docker Hub. As mentioned in [this issue](https://github.com/docker/hub-feedback/issues/1927), it seems that not only have [Personal Access Tokens](https://docs.docker.com/docker-hub/access-tokens/) stopped working, but the new 2FA feature also does not allow this type of access (which makes sense). I will update the README to make it more clear.

Unfortunately, there is no good solution at the moment until Docker Hub allow Personal Access Tokens to be used with the particular API in use by this action. The only option right now is to disable 2FA if you want to use this action.

**Comment by Erikvl87** [comment]
Ah, thanks @peter-evans. It does make sense indeed, although I do not feel too comfortable to compromise on security by disabling 2FA (which is kind of ironic in this case 😄).

I think I will revert back to manually updating the Docker Hub Description and wait for scope support on tokens to allow other APIs, as mentioned in the referenced issue. Hope they will do that soon, so I can use your action again.

**Comment by peter-evans** [comment]
Sorry I can't be more help at the moment. Hope they add scopes for the API soon.

I'll close this issue for now.
